[package]
name = "optimistic-derives"
version = "0.1.0"
edition = "2018"

[lib]
crate_type = ["proc-macro"]

[dependencies]
proc-macro2 = "1.0"
quote = "1.0"
serde = { version = "1.0", features = ["derive"] }
syn = "1.0"